### ISSUE TITLE
Selenium WebDriver.py Error

### ISSUE THREAD

**Issue by NateDevOfficial** [Nemixalone/GUI-tool-for-InstaPy-script#6]
I used the InstaPy GUI application on Windows 10 64-bit and I set everything up, and hit run. It then opened for about 1 second and then closed. The error was:

Traceback: (most recent call last):
File "quickstart.py", line 3, in <module>
     session - InstaPy(username-"", password-"")
File "\InstaPy\instapy\instapy.py", line 37, in __init__
It continues: http://imgur.com/a/h1x9W

**Comment by Nemixalone** [comment]
Since this is InstaPy error and its not related with GUI, I am not fitting person to respond and give any solution regarding this error. Can you please post this issue on official [InstaPy issues](https://github.com/timgrossmann/InstaPy/issues) page. And I highly recommend to mark out username and password from image. I hope you get the solution for problem. :)
