### ISSUE TITLE
Everything is complete but.....

### ISSUE THREAD

**Issue by chitomod** [Nemixalone/GUI-tool-for-InstaPy-script#8]
I have done everything and the app says "All instaPY files are there" but when I start the app, it opens cmd and closes about 1 sec, and when i check my instagram profile it is not liking or following anyone.

**Comment by Nemixalone** [comment]
Since it's the InstaPy error not the GUI, I am gonna ask you to do the following
Go to InstaPy folder press **SHIFT** then **right click**
Click on **Open command window here**
Type **py quickstart.py**
Copy error message and open Issue on Official [InstaPy](https://github.com/timgrossmann/InstaPy) page.
Thanks :smile:
